#!/usr/bin/env sh

commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")

pattern="^(feat|fix|chore): .+"

if ! echo "$commit_msg" | grep -Eq "$pattern"; then
  echo "❌ Commit bloqueado: mensagem inválida"
  echo ""
  echo "Use um dos padrões abaixo:"
  echo "  feat: descrição clara"
  echo "  fix: descrição clara"
  echo "  chore: descrição clara"
  exit 1
fi

exit 0
